{
 "title": "Endterm Services Dashboard",
 "tags": [
  "endterm",
  "sre"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Average Uptime Probe Success",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(probe_success)" }
   ]
  },
  {
   "title": "Service Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\".*_http_requests_total\"}[5m])) by (job)"
    }
   ]
  },
  {
   "title": "Service Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\".*_http_requests_total\", status_code=~\"5..\"}[5m])) by (job)"
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\"}[5m])) by (name)"
    }
   ]
  }
 ]
}