apiVersion: v1
kind: Service
metadata:
  name: postgres-primary-headless
  namespace: endterm
spec:
  clusterIP: None
  selector:
    app: postgres-primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
  namespace: endterm
  labels:
    app: postgres-primary
spec:
  selector:
    app: postgres-primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replicas
  namespace: endterm
  labels:
    app: postgres-replica
spec:
  selector:
    app: postgres-replica
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica-headless
  namespace: endterm
spec:
  clusterIP: None
  selector:
    app: postgres-replica
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
